package mvpdemo.hd.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import mvpdemo.hd.greendao.entity.Groups;
import mvpdemo.hd.greendao.entity.Word;
import mvpdemo.hd.greendao.entity.Setting;

import mvpdemo.hd.greendao.GroupsDao;
import mvpdemo.hd.greendao.WordDao;
import mvpdemo.hd.greendao.SettingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupsDaoConfig;
    private final DaoConfig wordDaoConfig;
    private final DaoConfig settingDaoConfig;

    private final GroupsDao groupsDao;
    private final WordDao wordDao;
    private final SettingDao settingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupsDaoConfig = daoConfigMap.get(GroupsDao.class).clone();
        groupsDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        settingDaoConfig = daoConfigMap.get(SettingDao.class).clone();
        settingDaoConfig.initIdentityScope(type);

        groupsDao = new GroupsDao(groupsDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);
        settingDao = new SettingDao(settingDaoConfig, this);

        registerDao(Groups.class, groupsDao);
        registerDao(Word.class, wordDao);
        registerDao(Setting.class, settingDao);
    }
    
    public void clear() {
        groupsDaoConfig.clearIdentityScope();
        wordDaoConfig.clearIdentityScope();
        settingDaoConfig.clearIdentityScope();
    }

    public GroupsDao getGroupsDao() {
        return groupsDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

    public SettingDao getSettingDao() {
        return settingDao;
    }

}
