package mvpdemo.hd.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import mvpdemo.hd.greendao.entity.Setting;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SETTING".
*/
public class SettingDao extends AbstractDao<Setting, Long> {

    public static final String TABLENAME = "SETTING";

    /**
     * Properties of entity Setting.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property DisplaySpell = new Property(1, int.class, "displaySpell", false, "DISPLAY_SPELL");
        public final static Property DisplayMeaning = new Property(2, int.class, "displayMeaning", false, "DISPLAY_MEANING");
        public final static Property Intervals = new Property(3, int.class, "intervals", false, "INTERVALS");
        public final static Property Repeated = new Property(4, int.class, "repeated", false, "REPEATED");
        public final static Property Random = new Property(5, int.class, "random", false, "RANDOM");
    }


    public SettingDao(DaoConfig config) {
        super(config);
    }
    
    public SettingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SETTING\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"DISPLAY_SPELL\" INTEGER NOT NULL ," + // 1: displaySpell
                "\"DISPLAY_MEANING\" INTEGER NOT NULL ," + // 2: displayMeaning
                "\"INTERVALS\" INTEGER NOT NULL ," + // 3: intervals
                "\"REPEATED\" INTEGER NOT NULL ," + // 4: repeated
                "\"RANDOM\" INTEGER NOT NULL );"); // 5: random
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SETTING\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Setting entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getDisplaySpell());
        stmt.bindLong(3, entity.getDisplayMeaning());
        stmt.bindLong(4, entity.getIntervals());
        stmt.bindLong(5, entity.getRepeated());
        stmt.bindLong(6, entity.getRandom());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Setting entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getDisplaySpell());
        stmt.bindLong(3, entity.getDisplayMeaning());
        stmt.bindLong(4, entity.getIntervals());
        stmt.bindLong(5, entity.getRepeated());
        stmt.bindLong(6, entity.getRandom());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Setting readEntity(Cursor cursor, int offset) {
        Setting entity = new Setting( //
            cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // displaySpell
            cursor.getInt(offset + 2), // displayMeaning
            cursor.getInt(offset + 3), // intervals
            cursor.getInt(offset + 4), // repeated
            cursor.getInt(offset + 5) // random
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Setting entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setDisplaySpell(cursor.getInt(offset + 1));
        entity.setDisplayMeaning(cursor.getInt(offset + 2));
        entity.setIntervals(cursor.getInt(offset + 3));
        entity.setRepeated(cursor.getInt(offset + 4));
        entity.setRandom(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Setting entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Setting entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Setting entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
